/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Mon Jan 06 11:15:36 EST 2020 ----! */

#include <jni.h>
#include <stdlib.h>

#include <assert.h>


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: int sqlc_db_close(long db)
 *     C function: int sqlc_db_close(sqlc_handle_t db);
 */
JNIEXPORT jint JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1db_1close__J(JNIEnv *env, jclass _unused, jlong db) {
  int _res;
  _res = sqlc_db_close((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: int sqlc_db_errcode(long db)
 *     C function: int sqlc_db_errcode(sqlc_handle_t db);
 */
JNIEXPORT jint JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1db_1errcode__J(JNIEnv *env, jclass _unused, jlong db) {
  int _res;
  _res = sqlc_db_errcode((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: java.lang.String sqlc_db_errmsg_native(long db)
 *     C function: const char *  sqlc_db_errmsg_native(sqlc_handle_t db);
 */
JNIEXPORT jstring JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1db_1errmsg_1native__J(JNIEnv *env, jclass _unused, jlong db) {
  const char *  _res;
  _res = sqlc_db_errmsg_native((sqlc_handle_t) db);
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: long sqlc_db_last_insert_rowid(long db)
 *     C function: sqlc_long_t sqlc_db_last_insert_rowid(sqlc_handle_t db);
 */
JNIEXPORT jlong JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1db_1last_1insert_1rowid__J(JNIEnv *env, jclass _unused, jlong db) {
  sqlc_long_t _res;
  _res = sqlc_db_last_insert_rowid((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: int sqlc_db_total_changes(long db)
 *     C function: int sqlc_db_total_changes(sqlc_handle_t db);
 */
JNIEXPORT jint JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1db_1total_1changes__J(JNIEnv *env, jclass _unused, jlong db) {
  int _res;
  _res = sqlc_db_total_changes((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: java.lang.String sqlc_errstr_native(int errcode)
 *     C function: const char *  sqlc_errstr_native(int errcode);
 */
JNIEXPORT jstring JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1errstr_1native__I(JNIEnv *env, jclass _unused, jint errcode) {
  const char *  _res;
  _res = sqlc_errstr_native((int) errcode);
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: long sqlc_evplus_db_new_qc(long db)
 *     C function: sqlc_handle_t sqlc_evplus_db_new_qc(sqlc_handle_t db);
 */
JNIEXPORT jlong JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1evplus_1db_1new_1qc__J(JNIEnv *env, jclass _unused, jlong db) {
  sqlc_handle_t _res;
  _res = sqlc_evplus_db_new_qc((sqlc_handle_t) db);
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: long sqlc_evplus_db_open(int sqlc_evplus_api_version, java.lang.String filename, int flags)
 *     C function: sqlc_handle_t sqlc_evplus_db_open(int sqlc_evplus_api_version, const char *  filename, int flags);
 */
JNIEXPORT jlong JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1evplus_1db_1open__ILjava_lang_String_2I(JNIEnv *env, jclass _unused, jint sqlc_evplus_api_version, jstring filename, jint flags) {
  const char* _strchars_filename = NULL;
  sqlc_handle_t _res;
  if ( NULL != filename ) {
    _strchars_filename = (*env)->GetStringUTFChars(env, filename, (jboolean*)NULL);
  if ( NULL == _strchars_filename ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"filename\" in native dispatcher for \"sqlc_evplus_db_open\"");
      return 0;
    }
  }
  _res = sqlc_evplus_db_open((int) sqlc_evplus_api_version, (char *) _strchars_filename, (int) flags);
  if ( NULL != filename ) {
    (*env)->ReleaseStringUTFChars(env, filename, _strchars_filename);
  }
  return _res;
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: java.lang.String sqlc_evplus_qc_execute(long qc, java.lang.String batch_json)
 *     C function: const char *  sqlc_evplus_qc_execute(sqlc_handle_t qc, const char *  batch_json);
 */
JNIEXPORT jstring JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1evplus_1qc_1execute__JLjava_lang_String_2(JNIEnv *env, jclass _unused, jlong qc, jstring batch_json) {
  const char* _strchars_batch_json = NULL;
  const char *  _res;
  if ( NULL != batch_json ) {
    _strchars_batch_json = (*env)->GetStringUTFChars(env, batch_json, (jboolean*)NULL);
  if ( NULL == _strchars_batch_json ) {
      (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/OutOfMemoryError"),
                       "Failed to get UTF-8 chars for argument \"batch_json\" in native dispatcher for \"sqlc_evplus_qc_execute\"");
      return 0;
    }
  }
  _res = sqlc_evplus_qc_execute((sqlc_handle_t) qc, (char *) _strchars_batch_json);
  if ( NULL != batch_json ) {
    (*env)->ReleaseStringUTFChars(env, batch_json, _strchars_batch_json);
  }
  if (NULL == _res) return NULL;
  return (*env)->NewStringUTF(env, _res);
}


/*   Java->C glue code:
 *   Java package: io.sqlc.EVPlusNativeDriver
 *    Java method: void sqlc_evplus_qc_finalize(long qc)
 *     C function: void sqlc_evplus_qc_finalize(sqlc_handle_t qc);
 */
JNIEXPORT void JNICALL 
Java_io_sqlc_EVPlusNativeDriver_sqlc_1evplus_1qc_1finalize__J(JNIEnv *env, jclass _unused, jlong qc) {
  sqlc_evplus_qc_finalize((sqlc_handle_t) qc);
}


